"""This file was generated by AppSecAI to validate the fix for CWE-89 in demo/vulnerable_web_app.py:148.
Inputs below are representative attacks for this CWE and should be rejected by the fix. Delete or edit this file after review.
"""

import pytest


MALICIOUS_INPUTS = ["' OR '1'='1", "'; DROP TABLE users; --"]
SAFE_INPUTS = ['customer-123', 'invoice-42']


@pytest.mark.skip(reason="Wire this generated test to the fixed entry point before relying on it in CI.")
def test_cwe_89_generated_negative_case():
    assert MALICIOUS_INPUTS
    assert SAFE_INPUTS
