"""This file was generated by AppSecAI to validate the fix for CWE-78 in demo/vulnerable_devops_automation.py:197.
Inputs below are representative attacks for this CWE and should be rejected by the fix. Delete or edit this file after review.
"""

import pytest


MALICIOUS_INPUTS = ['test; cat /etc/passwd', '$(whoami)']
SAFE_INPUTS = ['customer-sync', 'daily-report']


@pytest.mark.skip(reason="Wire this generated test to the fixed entry point before relying on it in CI.")
def test_cwe_78_generated_negative_case():
    assert MALICIOUS_INPUTS
    assert SAFE_INPUTS
