"""This file was generated by AppSecAI to validate the fix for CWE-798 in examples/unsafe.py:86.
Inputs below are representative attacks for this CWE and should be rejected by the fix. Delete or edit this file after review.
"""

import pytest


MALICIOUS_INPUTS = ['hardcoded-admin-token', 'prod-root-password']
SAFE_INPUTS = ['${APPSECAI_TEST_SECRET}', '${CUSTOMER_API_TOKEN}']


@pytest.mark.skip(reason="Wire this generated test to the fixed entry point before relying on it in CI.")
def test_cwe_798_generated_negative_case():
    assert MALICIOUS_INPUTS
    assert SAFE_INPUTS
