"""This file was generated by AppSecAI to validate the fix for CWE-502 in demo/vulnerable.py:33.
Inputs below are representative attacks for this CWE and should be rejected by the fix. Delete or edit this file after review.
"""

import pytest


MALICIOUS_INPUTS = ['{"__reduce__":"os.system"}', 'rO0ABXNyAA...']
SAFE_INPUTS = ['{"user":"alice"}', '{"items":[1,2,3]}']


@pytest.mark.skip(reason="Wire this generated test to the fixed entry point before relying on it in CI.")
def test_cwe_502_generated_negative_case():
    assert MALICIOUS_INPUTS
    assert SAFE_INPUTS
